from __future__ import annotations

import argparse
import csv
import random
import shutil
from collections import defaultdict
from pathlib import Path

LABELS = ("A", "Am", "B", "Bm", "C", "Cm", "D", "Dm", "E", "Em", "F", "Fm", "G", "Gm")


def link_or_copy(source: Path, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() and target.stat().st_size == source.stat().st_size:
        return
    if target.exists():
        target.unlink()
    try:
        target.hardlink_to(source)
    except OSError:
        shutil.copy2(source, target)


def split_group(items: list[dict[str, str]], val_ratio: float, test_ratio: float) -> dict[str, list[dict[str, str]]]:
    total = len(items)
    test_count = max(1, round(total * test_ratio))
    val_count = max(1, round(total * val_ratio))
    train_count = max(1, total - val_count - test_count)

    if train_count + val_count + test_count > total:
        train_count = max(1, total - val_count - test_count)

    return {
        "train": items[:train_count],
        "val": items[train_count : train_count + val_count],
        "test": items[train_count + val_count : train_count + val_count + test_count],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Create a stratified Ultralytics classification split from the HF manifest.")
    parser.add_argument("--source-root", default="data/hf_guitar_chords", help="Folder containing the downloaded HF images.")
    parser.add_argument("--manifest", default="data/hf_guitar_chords/manifest.csv", help="Manifest generated by download_hf_guitar_chords.py.")
    parser.add_argument("--out", default="data/hf_guitar_chords_yolo", help="Output folder for YOLO classification.")
    parser.add_argument("--val-ratio", type=float, default=0.1)
    parser.add_argument("--test-ratio", type=float, default=0.1)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    source_root = Path(args.source_root)
    out_root = Path(args.out)

    by_label: dict[str, list[dict[str, str]]] = defaultdict(list)
    with Path(args.manifest).open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            by_label[row["label"]].append(row)

    random.seed(args.seed)
    summary_rows: list[dict[str, str | int]] = []
    for label in LABELS:
        rows = by_label[label]
        random.shuffle(rows)
        split_rows = split_group(rows, args.val_ratio, args.test_ratio)

        for split, items in split_rows.items():
            for item in items:
                source = source_root / item["relative_path"]
                target = out_root / split / label / f"{item['row_idx']}.jpg"
                link_or_copy(source, target)
            summary_rows.append({"split": split, "label": label, "count": len(items)})

    summary_path = out_root / "split_summary.csv"
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    with summary_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=["split", "label", "count"])
        writer.writeheader()
        writer.writerows(summary_rows)

    for split in ("train", "val", "test"):
        count = sum(int(row["count"]) for row in summary_rows if row["split"] == split)
        print(f"{split}: {count} images")
    print(f"Wrote YOLO classification dataset to {out_root}")


if __name__ == "__main__":
    main()
